Update symlink-scripts: Output warning to stderr

diff --git a/symlink-scripts b/symlink-scripts
--- a/symlink-scripts
+++ b/symlink-scripts
@@ -25,7 +25,7 @@ for scriptOriginalPath in $scriptPaths
   ln -s $scriptOriginalPath $symlinkFilepath
   if test $status -ne 0
     set_color red
-    echo "WARNING: failed to symlink $scriptName"
+    echo "WARNING: failed to symlink $scriptName" 1>&2
     set_color normal
   end
 end
